# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-otr}
  s.version = "0.0.0.beta0"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Marius Hanne}]
  s.date = %q{2011-10-29}
  s.description = %q{Off-The-Record messaging in Ruby. See http://www.cypherpunks.ca/otr/ for details on OTR.}
  s.email = %q{marius.hanne@sourceagency.org}
  s.extensions = [%q{ext/extconf.rb}]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".rspec",
    "COPYING",
    "README",
    "Rakefile",
    "doc/do.sh",
    "doc/hello_world.rb",
    "doc/jabber_echo_example.rb",
    "ext/extconf.rb",
    "ext/otr.c",
    "ext/ruby-otr.c",
    "ext/ruby-otr.h",
    "ext/uiops.c",
    "ext/userstate.c",
    "lib/otr.rb",
    "spec/fixtures/fingerprints_1.txt",
    "spec/fixtures/keys_1.txt",
    "spec/fixtures/keys_2.txt",
    "spec/otr/otr_spec.rb",
    "spec/otr/privkey_spec.rb",
    "spec/otr/userstate_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Ruby bindings for libotr}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

